### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Sonderwoods**
- Colors to show whether the run is set to true or false
- Multiple inputs for Pass can be added without running twice etc
- Added double click for instant single run
- Added timer for time since last run (only available when you zoomin on the component and if its 'closed'
- added an output for true/false of running. This is ALWAYS updated. Can be used to hide previews etc in GH.
- Overwritten existing component GUID. This 'should' be ok when upgrading since i am not adding new params and checking if 2nd output param exists before using it.

image

image

image

### CODE REVIEW

**Comment by Sonderwoods** [comment]
hi @Attemainio , Timo has tested this a bit and seems to him that this actually solves some issues he's had with the current version.

He is waiting for a new Yak release. I was wondering if you have had time to test it out yet, otherwise I'll make a quick and dirty yak in another plugin name for his customers.

**Comment by Sonderwoods** [comment]
Another feature that could be nice to add is if the pass goes from true -> true then it should NOT update.


Right now its:
True -> False : No update
False -> False: No Update
True -> True: Update         ( Maybe this should NOT update!?)
False -> True: Update

extraUpdate

**Comment by Sonderwoods** [comment]
sticky on is now working (can be toggled with a right click on the component)

extraUpdate22

**Comment by Attemainio** [comment]
Thanks for the comments! Today, I have some spare to dive deep into the suggestions. I'm creating a new branch for testing and reviewing purposes. I'll be adding previous yak packages and unit tests for the project as well.

EDIT: Created a new branch for testing and merged the commit of Mathias to the testing branch.

**Comments and merged improvements:**

1. Colors to show whether the run is set to true or false

The change in the color of the component is a great idea. However, the same functionality can be reached by changing the color of the component icon. Therefore, I removed all the component attributes related to rendering new colors for the canvas. In contrast, I used SetIconOverride() to control the icon color in the SolveInstance() method directly. Thus, the code remains more concise and simple providing the same functionality.

image

2. Multiple inputs for Pass can be added without running twice etc

While the multi-input and output seem to be a great idea, I decided to remove this functionality. The reason is that the input for the Pass argument can be constructed easily by logical gates. Gatekeeper only accepts one single data item for Pass input. Otherwise, it yields an error, and no data is passed forward. The original idea of the gatekeeper is to stop data to downstream objects, and not to duplicate in the component itself. If the duplication is desired, it can be achieved with other components. In 99% of the cases, it is easier to just use multiple Gatekeepers since pass argument for each component can be controlled by single boolean value.

image

3. Added double click for an instant single run

Approved.

4. Added timer for time since the last run (only available when you zoom in on the component and if it 'closed'

Great idea as well. However, I found it too clunky that the information is only updated when the GH canvas is rendered. Moreover, it is more efficient to use the component Message property instead of rendering direct text objects next to the component. Thus, I removed all the unnecessary render functions related to custom text renderings. Using a direct timestamp with the accuracy of seconds instead of period seems to be a better alternative.

image

5. Added an output for true/false of running. This is ALWAYS updated. Can be used to hide previews etc in GH.

Approved. However, this setting can be now tweaked by right-clicking the component and setting "Update Output" to true. I preserved the Read and Write functionalities also.

image

6. Overwritten existing component GUID. This 'should' be ok when upgrading since i am not adding new params and checking if 2nd output param exists before using it.

Declined. Original GUID is now present.

**Comment by Sonderwoods** [comment]
agreed on your changes. good arguments and i love the icon change.

Not sure what you mean with declined on the GUID. arent we saying the same?

In any case - i think the GUID should be the same as original. I only change GUIDs if params or functionality is changed.

I'll let timo know he can find it on Yak :D

**Comment by Attemainio** [comment]
I noticed that the GUID was changed, so I reverted it to the original one :D I found that GH_GatekeeperComponent_OLD had a different GUID than GH_GatekeeperComponent, and now the current solution has the GUID of GH_GatekeeperComponent_OLD. I already informed Timo about the yak package release. I do not change GUIDs ever, but I do not have a proper knowledge that when it should be changed.

**Comment by timonielsen** [comment]
You guys are amazing. I really really like the component! I have a project I'm working on that will put this to the ultimate stress test. I will let you know how it goes. We previously had everything collapsing, so let's see with this new update :)

**Comment by Attemainio** [comment]
Yeah, it has improved a lot 😄 We still have to find out why Gatekeeper prevents scriptcontext not to load, which I think is a part of GhPython.gha plugin

**Pull request merged**
